u = int(input('Enter the Initial velocity :'))
v = int(input('Enter the Final velocity :'))
a = int(input('Enter the Acceleration :'))
displacment = (v**2 - u**2) / (2 * a)
print('Displacement is ',displacment)